[general]

[window]
opacity = 0.9
decorations = "None"
startup_mode = "Maximized"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[colors.primary]
background = "#1E1E2E"
