"$schema" = 'https://starship.rs/config-schema.json'

format = """
(#9A348E)\
$directory\
$git_branch\
$git_status\
$kubernetes\
"""

# Disable the blank line at the start of the prompt
# add_newline = false


[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
style = 'blue'

[git_branch]
symbol = "⎇"
format = 'on[ $symbol $branch ]($style)'
style = 'green'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = 'green'
modified = "*"
staged   = "+"
untracked = "?"
ahead = "⇡"
behind = "⇣"
