"$schema" = 'https://starship.rs/config-schema.json'

format = """
(#9A348E)\
$directory\
$python\
$git_branch\
$git_status\
$character\
"""

right_format = """
$kubernetes\
"""

# Disable the blank line at the start of the prompt
# add_newline = false


[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
style = 'blue'

[python]
symbol = ""
format = '[ $symbol ($virtualenv) ]($style)'
style = 'blue'

[git_branch]
symbol = "⎇"
format = 'on[ $symbol $branch]($style)'
style = 'green'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = 'green'
modified = "*"
staged   = "+"
untracked = "?"
ahead = "⇡"
behind = "⇣"

[kubernetes]
disabled = false
format = '[$context( \($namespace\)) ]($style)'
style = 'cyan'

[[kubernetes.contexts]]
context_pattern = ".*prod.*"
style = 'red bold'

[[kubernetes.contexts]]
context_pattern = ".*poc.*"
style = 'red bold'

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
